### ISSUE TITLE
Feedback for Tech Challenge

### ISSUE THREAD

**Issue by marcoonroad** [allmonty/tech-challenge#1]
Overall good, despite some gotchas.

On `test/money_test.exs`, from line 66 upto line 84, we have duplicated code:

```elixir
  test "#new receiving a string in amount should return error", state do
    %{alph_code: alph_code, num_code: num_code, decimal_points: dec_points} = state.recipient

    amount = "teste"

    {resp, _response} = Money.new(amount, alph_code, num_code, dec_points)

    assert resp == :error
  end

  test "#new receiving nil in amount should return error", state do
    %{alph_code: alph_code, num_code: num_code, decimal_points: dec_points} = state.recipient

    amount = "teste"

    {resp, _response} = Money.new(amount, alph_code, num_code, dec_points)

    assert resp == :error
  end
```

On this latter test case, you should use `amount = nil` instead of `amount = "teste"`.

On `test/calculator_test.exs`, from line 23 upto 45, you're being too specific. You could collapse such test cases (assertions, more specifically) into a single one (made of 3 assertions):

```elixir
  test "#convert_currency should return money with the converted alph_code", state do
    %{money: money, currency_usd: currency} = state.recipient

    {:ok, converted_money} = Calculator.convert_currency(money, 0.31926, currency)

    assert converted_money.currency.alph_code == "USD"
  end

  test "#convert_currency should return money with the converted num_code", state do
    %{money: money, currency_usd: currency} = state.recipient

    {:ok, converted_money} = Calculator.convert_currency(money, 0.31926, currency)

    assert converted_money.currency.num_code == 840
  end

  test "#convert_currency should return money with the converted decimal_points", state do
    %{money: money, currency_usd: currency} = state.recipient

    {:ok, converted_money} = Calculator.convert_currency(money, 0.31926, currency)

    assert converted_money.currency.decimal_points == 2
  end
```

On `lib/financial_system.ex`, you have implemented float division (from line 117 upto 119):

```elixir
  defp divide_per_parts(num_of_parts, amount) do
    amount / num_of_parts
  end
```

This function is used by `calculate_money_per_part/1` (on the same file, lines 111-115), which is used by the public functions `payment_splitting_money_in_parts/3` and `transfer_splitting_money_in_parts/3`.

But this project is really fine, I've really liked it. :clap: :clap: :clap: :clap:

**Comment by allmonty** [comment]
But if i collapse the three tests, wouldn't it be problematic if two of the asserts fails at the same time? Because the test would stop in the first failed, what could lead to misunderstanding of the problem, don't you think?

**Comment by marcoonroad** [comment]
No, it would not be a problem. It doesn't matter the ordering when things fail, neither which things fail, so long as we break first and fix later. This is the golden rule to fix bugs: first we reproduce them on tests (failing the tests properly), and then we fix the bug on source code and pass the tests. This approach is used to avoid the reappearing of such bugs.

**Comment by marcoonroad** [comment]
To be honest, we shouldn't assume any prior ordering on tests. Otherwise, our tests could be biased in some sense.

**Comment by marcoonroad** [comment]
Oh, I forgot it entirely. In Elixir, we can pattern matching on test assertions, for instance:

```elixir
  test "#convert_currency", state do
    %{money: money, currency_usd: currency} = state.recipient

    {:ok, converted_money} = Calculator.convert_currency(money, 0.31926, currency)

    assert %FinancialSystem.Money{
      currency: %FinancialSystem.Currency{
        alph_code: "USD",
        num_code: 840,
        decimal_points: 2
      }
    } = converted_money
  end
```

👌 👌 👌 👌

**Comment by marcoonroad** [comment]
Let's close that, hahaha. :smile:
